version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - storage
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demopass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  storage:
    image: minio/minio:latest
    command: >
      server /data
      --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER: "on"
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  # Catálogo Bacula num Postgres dedicado
  catalog-db:
    image: postgres:15
    environment:
      POSTGRES_DB: bacula
      POSTGRES_USER: bacula
      POSTGRES_PASSWORD: bacula
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","bacula","-d","bacula"]
      interval: 5s
      retries: 5
  bacula-server:
    image: pwa666/bacula-server:11-postgresql-latest
    restart: unless-stopped
    depends_on:
      - catalog-db
      - storage
    environment:
      ## Banco de dados Bacula (catálogo)
      - DB_Host=catalog-db
      - DB_Port=5432
      - DB_User=bacula
      - DB_Password=bacula

      ## Diretório de working e storage
      - TZ=Europe/Lisbon
      - SD_Host=localhost

      ## Credenciais do Baculum (Web UI)
      - WEB_User=admin
      - WEB_Password=admin

      ## Notificações por email (opcional)
      - EMAIL_Recipient=you@domain.com
      - SMTP_Host=smtp.domain.com
      - SMTP_Port=587
      - SMTP_User=you@domain.com
      - SMTP_Password=yourpassword

    ports:
      - "9101:9101"   # Bacula Director
      - "9102:9102"   # Bacula File Daemon
      - "9103:9103"   # Bacula Storage Daemon
      - "9095:80"     # Baculum Web UI
      - "9096:9096"   # Baculum API
    volumes:
      - bacula-conf:/etc/bacula
      - baculum-conf:/etc/baculum
      - bacula-working:/var/lib/bacula
      - bacula-storage:/mnt/bacula
      - bacula-log:/var/log/bacula
      - apache-log:/var/log/apache2
      - minio_data:/minio_data:ro  # Mount MinIO data as read-only for backup
      - type: bind
        source: ../../bacula-server/conf/11/postgresql/bacula-dir.conf
        target: /etc/bacula/bacula-dir.conf
        read_only: true
      - type: bind
        source: ../../bacula-server/conf/11/postgresql/bacula-fd.conf
        target: /etc/bacula/bacula-fd.conf
        read_only: true
      - type: bind
        source: ../../bacula-server/conf/11/postgresql/bacula-sd.conf
        target: /etc/bacula/bacula-sd.conf
        read_only: true
      - type: bind
        source: ../../bacula-server/conf/bconsole.conf
        target: /etc/bacula/bconsole.conf
        read_only: true

volumes:
  db_data:
  minio_data:
  pgdata:
  bacula-conf:
  baculum-conf:
  bacula-working:
  bacula-storage:
  bacula-log:
  apache-log:
