version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demopass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  storage:
    image: minio/minio:latest
    command: >
      server /data
      --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER: "on"
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  # Catálogo Bacula num Postgres dedicado
  catalog-db:
    image: postgres:15
    environment:
      POSTGRES_DB: bacula
      POSTGRES_USER: bacula
      POSTGRES_PASSWORD: bacula
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","bacula","-d","bacula"]
      interval: 5s
      retries: 5

  # Novo serviço: Bacula Server + Baculum
  bacula-server:
    image: pwa666/bacula-server:11-postgresql-latest
    restart: unless-stopped
    depends_on:
      - catalog-db
    environment:
      ## Banco de dados Bacula (catálogo)
      - DB_Host=catalog-db                # host do Postgres de catálogo :contentReference[oaicite:1]{index=1}
      - DB_Port=5432
      - DB_User=bacula
      - DB_Password=bacula

      ## Diretório de working e storage
      - TZ=Europe/Lisbon
      - SD_Host=storage                   # host onde o Storage Daemon atende :contentReference[oaicite:2]{index=2}

      ## Credenciais do Baculum (Web UI)
      - WEB_User=admin
      - WEB_Password=difficult

      ## Notificações por email (opcional)
      - EMAIL_Recipient=you@domain.com
      - SMTP_Host=smtp.domain.com
      - SMTP_Port=587
      - SMTP_User=you@domain.com
      - SMTP_Password=yourpassword

    ports:
      - "9101:9101"   # Director
      - "9103:9103"   # Storage
      - "9095:9095"   # Baculum Web UI :contentReference[oaicite:3]{index=3}
      - "9096:9096"   # API
    volumes:
      - ../../bacula-server/conf/11/postgresql/bacula-dir.conf:/etc/bacula/bacula-dir.conf:ro
      - ../../bacula-server/conf/11/postgresql/bacula-fd.conf:/etc/bacula/bacula-fd.conf:ro
      - ../../bacula-server/conf/11/postgresql/bacula-sd.conf:/etc/bacula/bacula-sd.conf:ro
      - ../../bacula-server/conf/bconsole.conf:/etc/bacula/bconsole.conf:ro

volumes:
  db_data:
  minio_data:
  pgdata:
  bacula-conf:
  baculum-conf:
  bacula-working:
  bacula-storage:
  bacula-log:
  apache-log:
